name: Deploy Develop API-Server

on:
  push:
    branches:
      - main
    paths:
      - "Backend/src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: SSH 에이전트 설정
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.API_SERVER_SSH }}

      - name: 서버 배포
        id: deploy
        continue-on-error: true
        run: |
          set -o pipefail
          result=$(ssh -o StrictHostKeyChecking=no ${{ secrets.API_USER_NAME }}@${{ secrets.API_SERVER_ADDRESS }} << 'EOF'
            cd ~/lico/Backend/server/api || exit 1
            chmod +x deploy.sh || exit 1
            ./deploy.sh main || exit 1
          EOF
          )
          echo "DEPLOY_RESULT=${result}" >> $GITHUB_ENV

      - name: 결과 전송
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "server": "main",
            "result": "${{ env.DEPLOY_RESULT }}"
          }' ${{ secrets.WEBHOOK_URL }}
